ALTER TABLE t_p93404869_b2b_china_russia_1.products
  ADD COLUMN IF NOT EXISTS photos TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS sku VARCHAR(100),
  ADD COLUMN IF NOT EXISTS quantity VARCHAR(100),
  ADD COLUMN IF NOT EXISTS min_order VARCHAR(100);